//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Interface_Console.LOLConnect {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Device.DeviceTypes", Namespace="http://schemas.datacontract.org/2004/07/LOLAccountManagement")]
    public enum DeviceDeviceTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        iOS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Android = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Windows = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OSX = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XBOX360 = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountOAuth", Namespace="http://schemas.datacontract.org/2004/07/LOLAccountManagement")]
    [System.SerializableAttribute()]
    public partial class AccountOAuth : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AccountIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Test_Interface_Console.LOLConnect.GeneralError> ErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OAuthIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OAuthTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test_Interface_Console.LOLConnect.AccountOAuth.OAuthTypes OAuthTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AccountID {
            get {
                return this.AccountIDField;
            }
            set {
                if ((this.AccountIDField.Equals(value) != true)) {
                    this.AccountIDField = value;
                    this.RaisePropertyChanged("AccountID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Test_Interface_Console.LOLConnect.GeneralError> Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OAuthID {
            get {
                return this.OAuthIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OAuthIDField, value) != true)) {
                    this.OAuthIDField = value;
                    this.RaisePropertyChanged("OAuthID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OAuthToken {
            get {
                return this.OAuthTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.OAuthTokenField, value) != true)) {
                    this.OAuthTokenField = value;
                    this.RaisePropertyChanged("OAuthToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test_Interface_Console.LOLConnect.AccountOAuth.OAuthTypes OAuthType {
            get {
                return this.OAuthTypeField;
            }
            set {
                if ((this.OAuthTypeField.Equals(value) != true)) {
                    this.OAuthTypeField = value;
                    this.RaisePropertyChanged("OAuthType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="AccountOAuth.OAuthTypes", Namespace="http://schemas.datacontract.org/2004/07/LOLAccountManagement")]
        public enum OAuthTypes : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            LOL = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            FaceBook = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Google = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            YouTube = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            LinkedIn = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Twitter = 5,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/LOLAccountManagement")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AccountActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AccountIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Test_Interface_Console.LOLConnect.GeneralError> ErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasProfileImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PictureURLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AccountActive {
            get {
                return this.AccountActiveField;
            }
            set {
                if ((this.AccountActiveField.Equals(value) != true)) {
                    this.AccountActiveField = value;
                    this.RaisePropertyChanged("AccountActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AccountID {
            get {
                return this.AccountIDField;
            }
            set {
                if ((this.AccountIDField.Equals(value) != true)) {
                    this.AccountIDField = value;
                    this.RaisePropertyChanged("AccountID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Test_Interface_Console.LOLConnect.GeneralError> Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasProfileImage {
            get {
                return this.HasProfileImageField;
            }
            set {
                if ((this.HasProfileImageField.Equals(value) != true)) {
                    this.HasProfileImageField = value;
                    this.RaisePropertyChanged("HasProfileImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PictureURL {
            get {
                return this.PictureURLField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureURLField, value) != true)) {
                    this.PictureURLField = value;
                    this.RaisePropertyChanged("PictureURL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="General.Error", Namespace="http://schemas.datacontract.org/2004/07/LOLAccountManagement")]
    [System.SerializableAttribute()]
    public partial struct GeneralError : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test_Interface_Console.LOLConnect.SystemTypesErrorMessage ErrorTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescription {
            get {
                return this.ErrorDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescriptionField, value) != true)) {
                    this.ErrorDescriptionField = value;
                    this.RaisePropertyChanged("ErrorDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorLocation {
            get {
                return this.ErrorLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorLocationField, value) != true)) {
                    this.ErrorLocationField = value;
                    this.RaisePropertyChanged("ErrorLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorNumber {
            get {
                return this.ErrorNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorNumberField, value) != true)) {
                    this.ErrorNumberField = value;
                    this.RaisePropertyChanged("ErrorNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorTitle {
            get {
                return this.ErrorTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorTitleField, value) != true)) {
                    this.ErrorTitleField = value;
                    this.RaisePropertyChanged("ErrorTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test_Interface_Console.LOLConnect.SystemTypesErrorMessage ErrorType {
            get {
                return this.ErrorTypeField;
            }
            set {
                if ((this.ErrorTypeField.Equals(value) != true)) {
                    this.ErrorTypeField = value;
                    this.RaisePropertyChanged("ErrorType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemTypes.ErrorMessage", Namespace="http://schemas.datacontract.org/2004/07/LOLCodeLibrary.ErrorsManagement")]
    public enum SystemTypesErrorMessage : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthenticationTokenInvalid = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeviceIDMissing = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PasswordsDontMatch = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountInformationInvalid = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateEmailAddress = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountIDNull = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountIdDoesNotMatchDatabase = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeviceSaveFailed = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthenticationTokenDoesNotMatchAccountID = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthenticationTokenNotFound = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthenticationTokenLastUsedDateNotSet = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthenticationTokenExpired = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthenticationTokenNotLoggedIn = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthenticationTokenLoadFromDatarowFailed = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthenticationTokenLoadFailed = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthenticationTokenDeleteFailed = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthenticationTokenSaveFailed = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidUserInformation = 52,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NullEmailAddress = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResetPasswordFailed = 54,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidResetCode = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResetCodeExpired = 59,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResetPasswordFailed_NoMatchingEmailAddress = 61,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmailAddress = 62,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeviceNotRegisteredWithAnAccount = 63,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnknownUserContactRequested = 76,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateContact = 77,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountIDInvalid = 78,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OAuthTokenInvalid = 79,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OAuthIDInvalid = 80,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserGetSpecificFailed = 81,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthenticationTokenLoggedOut = 82,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unexpected = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CouldNotIdentifyRow = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContentPackIdMissing = 102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContentPackItemNotFound = 103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContentPackItemIdMissing = 104,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SearchCriteriaMissing = 105,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContactAccountIDMissing = 106,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ItemSizeNone = 107,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContactIDEmpty = 108,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContactNotFound = 109,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LOLConnect.ContactUpdate", Namespace="http://schemas.datacontract.org/2004/07/LOLAccountManagement")]
    [System.SerializableAttribute()]
    public partial struct LOLConnectContactUpdate : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<System.Guid> DeletedContactsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Test_Interface_Console.LOLConnect.GeneralError> ErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Test_Interface_Console.LOLConnect.Contact> UpdatedContactsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<System.Guid> DeletedContacts {
            get {
                return this.DeletedContactsField;
            }
            set {
                if ((object.ReferenceEquals(this.DeletedContactsField, value) != true)) {
                    this.DeletedContactsField = value;
                    this.RaisePropertyChanged("DeletedContacts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Test_Interface_Console.LOLConnect.GeneralError> Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Test_Interface_Console.LOLConnect.Contact> UpdatedContacts {
            get {
                return this.UpdatedContactsField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedContactsField, value) != true)) {
                    this.UpdatedContactsField = value;
                    this.RaisePropertyChanged("UpdatedContacts");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contact", Namespace="http://schemas.datacontract.org/2004/07/LOLAccountManagement")]
    [System.SerializableAttribute()]
    public partial class Contact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BlockedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ContactAccountIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ContactIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Test_Interface_Console.LOLConnect.Contact.ContactOAuth> ContactOAuthsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test_Interface_Console.LOLConnect.User ContactUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateLastUpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Test_Interface_Console.LOLConnect.GeneralError> ErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid OwnerAccountIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Blocked {
            get {
                return this.BlockedField;
            }
            set {
                if ((this.BlockedField.Equals(value) != true)) {
                    this.BlockedField = value;
                    this.RaisePropertyChanged("Blocked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ContactAccountID {
            get {
                return this.ContactAccountIDField;
            }
            set {
                if ((this.ContactAccountIDField.Equals(value) != true)) {
                    this.ContactAccountIDField = value;
                    this.RaisePropertyChanged("ContactAccountID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ContactID {
            get {
                return this.ContactIDField;
            }
            set {
                if ((this.ContactIDField.Equals(value) != true)) {
                    this.ContactIDField = value;
                    this.RaisePropertyChanged("ContactID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Test_Interface_Console.LOLConnect.Contact.ContactOAuth> ContactOAuths {
            get {
                return this.ContactOAuthsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactOAuthsField, value) != true)) {
                    this.ContactOAuthsField = value;
                    this.RaisePropertyChanged("ContactOAuths");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test_Interface_Console.LOLConnect.User ContactUser {
            get {
                return this.ContactUserField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactUserField, value) != true)) {
                    this.ContactUserField = value;
                    this.RaisePropertyChanged("ContactUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateLastUpdated {
            get {
                return this.DateLastUpdatedField;
            }
            set {
                if ((this.DateLastUpdatedField.Equals(value) != true)) {
                    this.DateLastUpdatedField = value;
                    this.RaisePropertyChanged("DateLastUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Test_Interface_Console.LOLConnect.GeneralError> Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OwnerAccountID {
            get {
                return this.OwnerAccountIDField;
            }
            set {
                if ((this.OwnerAccountIDField.Equals(value) != true)) {
                    this.OwnerAccountIDField = value;
                    this.RaisePropertyChanged("OwnerAccountID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Contact.ContactOAuth", Namespace="http://schemas.datacontract.org/2004/07/LOLAccountManagement")]
        [System.SerializableAttribute()]
        public partial struct ContactOAuth : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string OAuthIDField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private Test_Interface_Console.LOLConnect.AccountOAuth.OAuthTypes OAuthTypeField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string OAuthID {
                get {
                    return this.OAuthIDField;
                }
                set {
                    if ((object.ReferenceEquals(this.OAuthIDField, value) != true)) {
                        this.OAuthIDField = value;
                        this.RaisePropertyChanged("OAuthID");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public Test_Interface_Console.LOLConnect.AccountOAuth.OAuthTypes OAuthType {
                get {
                    return this.OAuthTypeField;
                }
                set {
                    if ((this.OAuthTypeField.Equals(value) != true)) {
                        this.OAuthTypeField = value;
                        this.RaisePropertyChanged("OAuthType");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LOLConnect.SearchCriteria", Namespace="http://schemas.datacontract.org/2004/07/LOLAccountManagement")]
    [System.SerializableAttribute()]
    public partial struct LOLConnectSearchCriteria : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OAuthIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test_Interface_Console.LOLConnect.AccountOAuth.OAuthTypes OAuthTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OAuthID {
            get {
                return this.OAuthIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OAuthIDField, value) != true)) {
                    this.OAuthIDField = value;
                    this.RaisePropertyChanged("OAuthID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test_Interface_Console.LOLConnect.AccountOAuth.OAuthTypes OAuthType {
            get {
                return this.OAuthTypeField;
            }
            set {
                if ((this.OAuthTypeField.Equals(value) != true)) {
                    this.OAuthTypeField = value;
                    this.RaisePropertyChanged("OAuthType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LOLConnect.SearchResult", Namespace="http://schemas.datacontract.org/2004/07/LOLAccountManagement")]
    [System.SerializableAttribute()]
    public partial struct LOLConnectSearchResult : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test_Interface_Console.LOLConnect.User ContactUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test_Interface_Console.LOLConnect.LOLConnectSearchCriteria SearchedCriteriaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test_Interface_Console.LOLConnect.User ContactUser {
            get {
                return this.ContactUserField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactUserField, value) != true)) {
                    this.ContactUserField = value;
                    this.RaisePropertyChanged("ContactUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test_Interface_Console.LOLConnect.LOLConnectSearchCriteria SearchedCriteria {
            get {
                return this.SearchedCriteriaField;
            }
            set {
                if ((this.SearchedCriteriaField.Equals(value) != true)) {
                    this.SearchedCriteriaField = value;
                    this.RaisePropertyChanged("SearchedCriteria");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LOLConnect.InviteEmail", Namespace="http://schemas.datacontract.org/2004/07/LOLAccountManagement")]
    [System.SerializableAttribute()]
    public partial struct LOLConnectInviteEmail : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test_Interface_Console.LOLConnect.AccountOAuth.OAuthTypes OAuthTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactName {
            get {
                return this.ContactNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNameField, value) != true)) {
                    this.ContactNameField = value;
                    this.RaisePropertyChanged("ContactName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test_Interface_Console.LOLConnect.AccountOAuth.OAuthTypes OAuthType {
            get {
                return this.OAuthTypeField;
            }
            set {
                if ((this.OAuthTypeField.Equals(value) != true)) {
                    this.OAuthTypeField = value;
                    this.RaisePropertyChanged("OAuthType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContentPack", Namespace="http://schemas.datacontract.org/2004/07/LOLAccountManagement")]
    [System.SerializableAttribute()]
    public partial class ContentPack : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ContentPackAdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ContentPackAvailableDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentPackDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ContentPackEndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContentPackIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ContentPackIconField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ContentPackIsFreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ContentPackPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ContentPackSaleEndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ContentPackSalePriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentPackTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test_Interface_Console.LOLConnect.ContentPack.ContentPackType ContentPackTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Test_Interface_Console.LOLConnect.GeneralError> ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ContentPackAd {
            get {
                return this.ContentPackAdField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentPackAdField, value) != true)) {
                    this.ContentPackAdField = value;
                    this.RaisePropertyChanged("ContentPackAd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ContentPackAvailableDate {
            get {
                return this.ContentPackAvailableDateField;
            }
            set {
                if ((this.ContentPackAvailableDateField.Equals(value) != true)) {
                    this.ContentPackAvailableDateField = value;
                    this.RaisePropertyChanged("ContentPackAvailableDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentPackDescription {
            get {
                return this.ContentPackDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentPackDescriptionField, value) != true)) {
                    this.ContentPackDescriptionField = value;
                    this.RaisePropertyChanged("ContentPackDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ContentPackEndDate {
            get {
                return this.ContentPackEndDateField;
            }
            set {
                if ((this.ContentPackEndDateField.Equals(value) != true)) {
                    this.ContentPackEndDateField = value;
                    this.RaisePropertyChanged("ContentPackEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContentPackID {
            get {
                return this.ContentPackIDField;
            }
            set {
                if ((this.ContentPackIDField.Equals(value) != true)) {
                    this.ContentPackIDField = value;
                    this.RaisePropertyChanged("ContentPackID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ContentPackIcon {
            get {
                return this.ContentPackIconField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentPackIconField, value) != true)) {
                    this.ContentPackIconField = value;
                    this.RaisePropertyChanged("ContentPackIcon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ContentPackIsFree {
            get {
                return this.ContentPackIsFreeField;
            }
            set {
                if ((this.ContentPackIsFreeField.Equals(value) != true)) {
                    this.ContentPackIsFreeField = value;
                    this.RaisePropertyChanged("ContentPackIsFree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ContentPackPrice {
            get {
                return this.ContentPackPriceField;
            }
            set {
                if ((this.ContentPackPriceField.Equals(value) != true)) {
                    this.ContentPackPriceField = value;
                    this.RaisePropertyChanged("ContentPackPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ContentPackSaleEndDate {
            get {
                return this.ContentPackSaleEndDateField;
            }
            set {
                if ((this.ContentPackSaleEndDateField.Equals(value) != true)) {
                    this.ContentPackSaleEndDateField = value;
                    this.RaisePropertyChanged("ContentPackSaleEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ContentPackSalePrice {
            get {
                return this.ContentPackSalePriceField;
            }
            set {
                if ((this.ContentPackSalePriceField.Equals(value) != true)) {
                    this.ContentPackSalePriceField = value;
                    this.RaisePropertyChanged("ContentPackSalePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentPackTitle {
            get {
                return this.ContentPackTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentPackTitleField, value) != true)) {
                    this.ContentPackTitleField = value;
                    this.RaisePropertyChanged("ContentPackTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test_Interface_Console.LOLConnect.ContentPack.ContentPackType ContentPackTypeID {
            get {
                return this.ContentPackTypeIDField;
            }
            set {
                if ((this.ContentPackTypeIDField.Equals(value) != true)) {
                    this.ContentPackTypeIDField = value;
                    this.RaisePropertyChanged("ContentPackTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Test_Interface_Console.LOLConnect.GeneralError> Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ContentPack.ContentPackType", Namespace="http://schemas.datacontract.org/2004/07/LOLAccountManagement")]
        public enum ContentPackType : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Comicon = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Comix = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            RubberStamp = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Callout = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SoundFX = 5,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Emoticon = 6,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContentPackItem", Namespace="http://schemas.datacontract.org/2004/07/LOLAccountManagement")]
    [System.SerializableAttribute()]
    public partial class ContentPackItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentItemTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ContentPackDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContentPackIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContentPackItemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ContentPackItemIconField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Test_Interface_Console.LOLConnect.GeneralError> ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentItemTitle {
            get {
                return this.ContentItemTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentItemTitleField, value) != true)) {
                    this.ContentItemTitleField = value;
                    this.RaisePropertyChanged("ContentItemTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ContentPackData {
            get {
                return this.ContentPackDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentPackDataField, value) != true)) {
                    this.ContentPackDataField = value;
                    this.RaisePropertyChanged("ContentPackData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContentPackID {
            get {
                return this.ContentPackIDField;
            }
            set {
                if ((this.ContentPackIDField.Equals(value) != true)) {
                    this.ContentPackIDField = value;
                    this.RaisePropertyChanged("ContentPackID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContentPackItemID {
            get {
                return this.ContentPackItemIDField;
            }
            set {
                if ((this.ContentPackItemIDField.Equals(value) != true)) {
                    this.ContentPackItemIDField = value;
                    this.RaisePropertyChanged("ContentPackItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ContentPackItemIcon {
            get {
                return this.ContentPackItemIconField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentPackItemIconField, value) != true)) {
                    this.ContentPackItemIconField = value;
                    this.RaisePropertyChanged("ContentPackItemIcon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Test_Interface_Console.LOLConnect.GeneralError> Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ContentPackItem.ItemSize", Namespace="http://schemas.datacontract.org/2004/07/LOLAccountManagement")]
        public enum ItemSize : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Large = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Medium = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Small = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Tiny = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            None = 4,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WcfBaseObject", Namespace="http://schemas.datacontract.org/2004/07/LOLAccountManagement.Classes")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Test_Interface_Console.LOLConnect.ContentPackItemListDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Test_Interface_Console.LOLConnect.UserImageDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Test_Interface_Console.LOLConnect.ContentPackItemDataDTO))]
    public partial class WcfBaseObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Test_Interface_Console.LOLConnect.GeneralError> ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Test_Interface_Console.LOLConnect.GeneralError> Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContentPackItemListDTO", Namespace="http://schemas.datacontract.org/2004/07/LOLAccountManagement.Classes.DtoObjects")]
    [System.SerializableAttribute()]
    public partial class ContentPackItemListDTO : Test_Interface_Console.LOLConnect.WcfBaseObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Test_Interface_Console.LOLConnect.ContentPackItem> contentPackItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Test_Interface_Console.LOLConnect.ContentPackItem> contentPackItems {
            get {
                return this.contentPackItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.contentPackItemsField, value) != true)) {
                    this.contentPackItemsField = value;
                    this.RaisePropertyChanged("contentPackItems");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserImageDTO", Namespace="http://schemas.datacontract.org/2004/07/LOLAccountManagement.Classes.DtoObjects")]
    [System.SerializableAttribute()]
    public partial class UserImageDTO : Test_Interface_Console.LOLConnect.WcfBaseObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AccountIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AccountID {
            get {
                return this.AccountIDField;
            }
            set {
                if ((this.AccountIDField.Equals(value) != true)) {
                    this.AccountIDField = value;
                    this.RaisePropertyChanged("AccountID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ImageData {
            get {
                return this.ImageDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageDataField, value) != true)) {
                    this.ImageDataField = value;
                    this.RaisePropertyChanged("ImageData");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContentPackItemDataDTO", Namespace="http://schemas.datacontract.org/2004/07/LOLAccountManagement.Classes.DtoObjects")]
    [System.SerializableAttribute()]
    public partial class ContentPackItemDataDTO : Test_Interface_Console.LOLConnect.WcfBaseObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ItemDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ItemData {
            get {
                return this.ItemDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemDataField, value) != true)) {
                    this.ItemDataField = value;
                    this.RaisePropertyChanged("ItemData");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="LOLConnect.LOLConnect")]
    public interface LOLConnect {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/AuthenticationTokenGet", ReplyAction="urn:LOLConnect/AuthenticationTokenGetResponse")]
        System.Guid AuthenticationTokenGet(string deviceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/UserLogin", ReplyAction="urn:LOLConnect/UserLoginResponse")]
        Test_Interface_Console.LOLConnect.User UserLogin(string deviceID, Test_Interface_Console.LOLConnect.DeviceDeviceTypes deviceType, System.Guid accountID, string oAuthID, string oAuthToken, Test_Interface_Console.LOLConnect.AccountOAuth.OAuthTypes oAuthType, string emailAddress, string password, System.Guid authenticationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/UserCreate", ReplyAction="urn:LOLConnect/UserCreateResponse")]
        Test_Interface_Console.LOLConnect.User UserCreate(string deviceID, Test_Interface_Console.LOLConnect.DeviceDeviceTypes deviceType, Test_Interface_Console.LOLConnect.AccountOAuth.OAuthTypes oAuthType, string oAuthID, string oAuthToken, string firstName, string lastName, string emailAddress, string password, byte[] picture, System.DateTime dateOfBirth, System.Guid authenticationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/UserGetSpecific", ReplyAction="urn:LOLConnect/UserGetSpecificResponse")]
        Test_Interface_Console.LOLConnect.User UserGetSpecific(System.Guid accountID, System.Guid targetAccountID, System.Guid authenticationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/UserSave", ReplyAction="urn:LOLConnect/UserSaveResponse")]
        Test_Interface_Console.LOLConnect.User UserSave(Test_Interface_Console.LOLConnect.User user, System.Guid authenticationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/UserLogOut", ReplyAction="urn:LOLConnect/UserLogOutResponse")]
        System.Collections.Generic.List<Test_Interface_Console.LOLConnect.GeneralError> UserLogOut(string deviceID, System.Guid accountID, System.Guid authenticationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/UserGetResetToken", ReplyAction="urn:LOLConnect/UserGetResetTokenResponse")]
        Test_Interface_Console.LOLConnect.GeneralError UserGetResetToken(string emailAddress, System.Guid authenticationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/UserPasswordReset", ReplyAction="urn:LOLConnect/UserPasswordResetResponse")]
        Test_Interface_Console.LOLConnect.User UserPasswordReset(string emailAddress, string resetToken, string password, System.Guid authenticationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/UserValidateResetToken", ReplyAction="urn:LOLConnect/UserValidateResetTokenResponse")]
        Test_Interface_Console.LOLConnect.GeneralError UserValidateResetToken(string emailAddress, string resetToken, System.Guid authenticationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/AccountOAuthCreate", ReplyAction="urn:LOLConnect/AccountOAuthCreateResponse")]
        Test_Interface_Console.LOLConnect.AccountOAuth AccountOAuthCreate(System.Guid accountID, Test_Interface_Console.LOLConnect.AccountOAuth.OAuthTypes oAuthType, string oAuthID, string oAuthToken, System.Guid authenticationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/ContactsGetUpdated", ReplyAction="urn:LOLConnect/ContactsGetUpdatedResponse")]
        Test_Interface_Console.LOLConnect.LOLConnectContactUpdate ContactsGetUpdated(System.Guid accountID, System.Collections.Generic.List<System.Guid> currentContacts, System.DateTime lastCallDate, System.Guid authenticationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/ContactsSearchList", ReplyAction="urn:LOLConnect/ContactsSearchListResponse")]
        System.Collections.Generic.List<Test_Interface_Console.LOLConnect.LOLConnectSearchResult> ContactsSearchList(System.Collections.Generic.List<Test_Interface_Console.LOLConnect.LOLConnectSearchCriteria> searchCriteria, System.Guid accountID, System.Guid authenticationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/ContactsSearch", ReplyAction="urn:LOLConnect/ContactsSearchResponse")]
        System.Collections.Generic.List<Test_Interface_Console.LOLConnect.LOLConnectSearchResult> ContactsSearch(Test_Interface_Console.LOLConnect.LOLConnectSearchCriteria searchCriteria, System.Guid accountID, System.Guid authenticationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/ContactsGetList", ReplyAction="urn:LOLConnect/ContactsGetListResponse")]
        System.Collections.Generic.List<Test_Interface_Console.LOLConnect.Contact> ContactsGetList(System.Guid accountID, System.Collections.Generic.List<System.Guid> excludeAccountIDs, System.Guid authenticationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/ContactGet", ReplyAction="urn:LOLConnect/ContactGetResponse")]
        Test_Interface_Console.LOLConnect.Contact ContactGet(System.Guid contactAccountID, System.Guid accountID, System.Guid authenticationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/ContactsSave", ReplyAction="urn:LOLConnect/ContactsSaveResponse")]
        Test_Interface_Console.LOLConnect.Contact ContactsSave(Test_Interface_Console.LOLConnect.Contact contact, System.Guid authenticationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/ContactsSaveList", ReplyAction="urn:LOLConnect/ContactsSaveListResponse")]
        System.Collections.Generic.List<Test_Interface_Console.LOLConnect.Contact> ContactsSaveList(System.Collections.Generic.List<Test_Interface_Console.LOLConnect.Contact> contacts, System.Guid authenticationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/ContactsDelete", ReplyAction="urn:LOLConnect/ContactsDeleteResponse")]
        System.Collections.Generic.List<Test_Interface_Console.LOLConnect.GeneralError> ContactsDelete(System.Guid contactID, System.Guid accountID, System.Guid authenticationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/ContactsSendInviteEmail", ReplyAction="urn:LOLConnect/ContactsSendInviteEmailResponse")]
        void ContactsSendInviteEmail(System.Collections.Generic.List<Test_Interface_Console.LOLConnect.LOLConnectInviteEmail> inviteEmails);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/ContentPacksGetByTypeAndAccountID", ReplyAction="urn:LOLConnect/ContentPacksGetByTypeAndAccountIDResponse")]
        System.Collections.Generic.List<Test_Interface_Console.LOLConnect.ContentPack> ContentPacksGetByTypeAndAccountID(System.Guid accountID, Test_Interface_Console.LOLConnect.ContentPack.ContentPackType contentPackType, System.Collections.Generic.List<int> excludeContentPackIDs, System.Guid authenticationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/ContentPacksGetByType", ReplyAction="urn:LOLConnect/ContentPacksGetByTypeResponse")]
        System.Collections.Generic.List<Test_Interface_Console.LOLConnect.ContentPack> ContentPacksGetByType(System.Guid accountID, Test_Interface_Console.LOLConnect.ContentPack.ContentPackType contentPackType, System.Guid authenticationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/ContentPackItemGetData", ReplyAction="urn:LOLConnect/ContentPackItemGetDataResponse")]
        Test_Interface_Console.LOLConnect.ContentPackItemDataDTO ContentPackItemGetData(int contentPackItemID, Test_Interface_Console.LOLConnect.ContentPackItem.ItemSize itemSize, System.Guid accountID, System.Guid authenticationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/ContentPackGetPackItemsLight", ReplyAction="urn:LOLConnect/ContentPackGetPackItemsLightResponse")]
        Test_Interface_Console.LOLConnect.ContentPackItemListDTO ContentPackGetPackItemsLight(int contentPackID, Test_Interface_Console.LOLConnect.ContentPackItem.ItemSize itemSize, System.Collections.Generic.List<int> excludeContentPackItemIDs, System.Guid accountID, System.Guid authenticationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/ContentPackGetPackItems", ReplyAction="urn:LOLConnect/ContentPackGetPackItemsResponse")]
        System.Collections.Generic.List<Test_Interface_Console.LOLConnect.ContentPackItem> ContentPackGetPackItems(int contentPackID, Test_Interface_Console.LOLConnect.ContentPackItem.ItemSize itemSize, System.Collections.Generic.List<int> excludeContentPackItemIDs, System.Guid accountID, System.Guid authenticationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/ContentPackGetItem", ReplyAction="urn:LOLConnect/ContentPackGetItemResponse")]
        Test_Interface_Console.LOLConnect.ContentPackItem ContentPackGetItem(int contentPackItemID, Test_Interface_Console.LOLConnect.ContentPackItem.ItemSize itemSize, System.Guid accountID, System.Guid authenticationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/ContentPackGetItemLight", ReplyAction="urn:LOLConnect/ContentPackGetItemLightResponse")]
        Test_Interface_Console.LOLConnect.ContentPackItem ContentPackGetItemLight(int contentPackItemID, Test_Interface_Console.LOLConnect.ContentPackItem.ItemSize itemSize, System.Guid accountID, System.Guid authenticationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/ContentPackGetItemIcon", ReplyAction="urn:LOLConnect/ContentPackGetItemIconResponse")]
        Test_Interface_Console.LOLConnect.ContentPackItemDataDTO ContentPackGetItemIcon(int contentPackItemID, Test_Interface_Console.LOLConnect.ContentPackItem.ItemSize itemSize, System.Guid accountID, System.Guid authenticationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/DeleteTestData", ReplyAction="urn:LOLConnect/DeleteTestDataResponse")]
        void DeleteTestData();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/GetVersionNumber", ReplyAction="urn:LOLConnect/GetVersionNumberResponse")]
        string GetVersionNumber(Test_Interface_Console.LOLConnect.DeviceDeviceTypes deviceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LOLConnect/UserGetImageData", ReplyAction="urn:LOLConnect/UserGetImageDataResponse")]
        Test_Interface_Console.LOLConnect.UserImageDTO UserGetImageData(System.Guid accountID, System.Guid requestedAccountID, System.Guid token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LOLConnectChannel : Test_Interface_Console.LOLConnect.LOLConnect, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LOLConnectClient : System.ServiceModel.ClientBase<Test_Interface_Console.LOLConnect.LOLConnect>, Test_Interface_Console.LOLConnect.LOLConnect {
        
        public LOLConnectClient() {
        }
        
        public LOLConnectClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LOLConnectClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LOLConnectClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LOLConnectClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid AuthenticationTokenGet(string deviceID) {
            return base.Channel.AuthenticationTokenGet(deviceID);
        }
        
        public Test_Interface_Console.LOLConnect.User UserLogin(string deviceID, Test_Interface_Console.LOLConnect.DeviceDeviceTypes deviceType, System.Guid accountID, string oAuthID, string oAuthToken, Test_Interface_Console.LOLConnect.AccountOAuth.OAuthTypes oAuthType, string emailAddress, string password, System.Guid authenticationToken) {
            return base.Channel.UserLogin(deviceID, deviceType, accountID, oAuthID, oAuthToken, oAuthType, emailAddress, password, authenticationToken);
        }
        
        public Test_Interface_Console.LOLConnect.User UserCreate(string deviceID, Test_Interface_Console.LOLConnect.DeviceDeviceTypes deviceType, Test_Interface_Console.LOLConnect.AccountOAuth.OAuthTypes oAuthType, string oAuthID, string oAuthToken, string firstName, string lastName, string emailAddress, string password, byte[] picture, System.DateTime dateOfBirth, System.Guid authenticationToken) {
            return base.Channel.UserCreate(deviceID, deviceType, oAuthType, oAuthID, oAuthToken, firstName, lastName, emailAddress, password, picture, dateOfBirth, authenticationToken);
        }
        
        public Test_Interface_Console.LOLConnect.User UserGetSpecific(System.Guid accountID, System.Guid targetAccountID, System.Guid authenticationToken) {
            return base.Channel.UserGetSpecific(accountID, targetAccountID, authenticationToken);
        }
        
        public Test_Interface_Console.LOLConnect.User UserSave(Test_Interface_Console.LOLConnect.User user, System.Guid authenticationToken) {
            return base.Channel.UserSave(user, authenticationToken);
        }
        
        public System.Collections.Generic.List<Test_Interface_Console.LOLConnect.GeneralError> UserLogOut(string deviceID, System.Guid accountID, System.Guid authenticationToken) {
            return base.Channel.UserLogOut(deviceID, accountID, authenticationToken);
        }
        
        public Test_Interface_Console.LOLConnect.GeneralError UserGetResetToken(string emailAddress, System.Guid authenticationToken) {
            return base.Channel.UserGetResetToken(emailAddress, authenticationToken);
        }
        
        public Test_Interface_Console.LOLConnect.User UserPasswordReset(string emailAddress, string resetToken, string password, System.Guid authenticationToken) {
            return base.Channel.UserPasswordReset(emailAddress, resetToken, password, authenticationToken);
        }
        
        public Test_Interface_Console.LOLConnect.GeneralError UserValidateResetToken(string emailAddress, string resetToken, System.Guid authenticationToken) {
            return base.Channel.UserValidateResetToken(emailAddress, resetToken, authenticationToken);
        }
        
        public Test_Interface_Console.LOLConnect.AccountOAuth AccountOAuthCreate(System.Guid accountID, Test_Interface_Console.LOLConnect.AccountOAuth.OAuthTypes oAuthType, string oAuthID, string oAuthToken, System.Guid authenticationToken) {
            return base.Channel.AccountOAuthCreate(accountID, oAuthType, oAuthID, oAuthToken, authenticationToken);
        }
        
        public Test_Interface_Console.LOLConnect.LOLConnectContactUpdate ContactsGetUpdated(System.Guid accountID, System.Collections.Generic.List<System.Guid> currentContacts, System.DateTime lastCallDate, System.Guid authenticationToken) {
            return base.Channel.ContactsGetUpdated(accountID, currentContacts, lastCallDate, authenticationToken);
        }
        
        public System.Collections.Generic.List<Test_Interface_Console.LOLConnect.LOLConnectSearchResult> ContactsSearchList(System.Collections.Generic.List<Test_Interface_Console.LOLConnect.LOLConnectSearchCriteria> searchCriteria, System.Guid accountID, System.Guid authenticationToken) {
            return base.Channel.ContactsSearchList(searchCriteria, accountID, authenticationToken);
        }
        
        public System.Collections.Generic.List<Test_Interface_Console.LOLConnect.LOLConnectSearchResult> ContactsSearch(Test_Interface_Console.LOLConnect.LOLConnectSearchCriteria searchCriteria, System.Guid accountID, System.Guid authenticationToken) {
            return base.Channel.ContactsSearch(searchCriteria, accountID, authenticationToken);
        }
        
        public System.Collections.Generic.List<Test_Interface_Console.LOLConnect.Contact> ContactsGetList(System.Guid accountID, System.Collections.Generic.List<System.Guid> excludeAccountIDs, System.Guid authenticationToken) {
            return base.Channel.ContactsGetList(accountID, excludeAccountIDs, authenticationToken);
        }
        
        public Test_Interface_Console.LOLConnect.Contact ContactGet(System.Guid contactAccountID, System.Guid accountID, System.Guid authenticationToken) {
            return base.Channel.ContactGet(contactAccountID, accountID, authenticationToken);
        }
        
        public Test_Interface_Console.LOLConnect.Contact ContactsSave(Test_Interface_Console.LOLConnect.Contact contact, System.Guid authenticationToken) {
            return base.Channel.ContactsSave(contact, authenticationToken);
        }
        
        public System.Collections.Generic.List<Test_Interface_Console.LOLConnect.Contact> ContactsSaveList(System.Collections.Generic.List<Test_Interface_Console.LOLConnect.Contact> contacts, System.Guid authenticationToken) {
            return base.Channel.ContactsSaveList(contacts, authenticationToken);
        }
        
        public System.Collections.Generic.List<Test_Interface_Console.LOLConnect.GeneralError> ContactsDelete(System.Guid contactID, System.Guid accountID, System.Guid authenticationToken) {
            return base.Channel.ContactsDelete(contactID, accountID, authenticationToken);
        }
        
        public void ContactsSendInviteEmail(System.Collections.Generic.List<Test_Interface_Console.LOLConnect.LOLConnectInviteEmail> inviteEmails) {
            base.Channel.ContactsSendInviteEmail(inviteEmails);
        }
        
        public System.Collections.Generic.List<Test_Interface_Console.LOLConnect.ContentPack> ContentPacksGetByTypeAndAccountID(System.Guid accountID, Test_Interface_Console.LOLConnect.ContentPack.ContentPackType contentPackType, System.Collections.Generic.List<int> excludeContentPackIDs, System.Guid authenticationToken) {
            return base.Channel.ContentPacksGetByTypeAndAccountID(accountID, contentPackType, excludeContentPackIDs, authenticationToken);
        }
        
        public System.Collections.Generic.List<Test_Interface_Console.LOLConnect.ContentPack> ContentPacksGetByType(System.Guid accountID, Test_Interface_Console.LOLConnect.ContentPack.ContentPackType contentPackType, System.Guid authenticationToken) {
            return base.Channel.ContentPacksGetByType(accountID, contentPackType, authenticationToken);
        }
        
        public Test_Interface_Console.LOLConnect.ContentPackItemDataDTO ContentPackItemGetData(int contentPackItemID, Test_Interface_Console.LOLConnect.ContentPackItem.ItemSize itemSize, System.Guid accountID, System.Guid authenticationToken) {
            return base.Channel.ContentPackItemGetData(contentPackItemID, itemSize, accountID, authenticationToken);
        }
        
        public Test_Interface_Console.LOLConnect.ContentPackItemListDTO ContentPackGetPackItemsLight(int contentPackID, Test_Interface_Console.LOLConnect.ContentPackItem.ItemSize itemSize, System.Collections.Generic.List<int> excludeContentPackItemIDs, System.Guid accountID, System.Guid authenticationToken) {
            return base.Channel.ContentPackGetPackItemsLight(contentPackID, itemSize, excludeContentPackItemIDs, accountID, authenticationToken);
        }
        
        public System.Collections.Generic.List<Test_Interface_Console.LOLConnect.ContentPackItem> ContentPackGetPackItems(int contentPackID, Test_Interface_Console.LOLConnect.ContentPackItem.ItemSize itemSize, System.Collections.Generic.List<int> excludeContentPackItemIDs, System.Guid accountID, System.Guid authenticationToken) {
            return base.Channel.ContentPackGetPackItems(contentPackID, itemSize, excludeContentPackItemIDs, accountID, authenticationToken);
        }
        
        public Test_Interface_Console.LOLConnect.ContentPackItem ContentPackGetItem(int contentPackItemID, Test_Interface_Console.LOLConnect.ContentPackItem.ItemSize itemSize, System.Guid accountID, System.Guid authenticationToken) {
            return base.Channel.ContentPackGetItem(contentPackItemID, itemSize, accountID, authenticationToken);
        }
        
        public Test_Interface_Console.LOLConnect.ContentPackItem ContentPackGetItemLight(int contentPackItemID, Test_Interface_Console.LOLConnect.ContentPackItem.ItemSize itemSize, System.Guid accountID, System.Guid authenticationToken) {
            return base.Channel.ContentPackGetItemLight(contentPackItemID, itemSize, accountID, authenticationToken);
        }
        
        public Test_Interface_Console.LOLConnect.ContentPackItemDataDTO ContentPackGetItemIcon(int contentPackItemID, Test_Interface_Console.LOLConnect.ContentPackItem.ItemSize itemSize, System.Guid accountID, System.Guid authenticationToken) {
            return base.Channel.ContentPackGetItemIcon(contentPackItemID, itemSize, accountID, authenticationToken);
        }
        
        public void DeleteTestData() {
            base.Channel.DeleteTestData();
        }
        
        public string GetVersionNumber(Test_Interface_Console.LOLConnect.DeviceDeviceTypes deviceType) {
            return base.Channel.GetVersionNumber(deviceType);
        }
        
        public Test_Interface_Console.LOLConnect.UserImageDTO UserGetImageData(System.Guid accountID, System.Guid requestedAccountID, System.Guid token) {
            return base.Channel.UserGetImageData(accountID, requestedAccountID, token);
        }
    }
}
