//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Interface.LOLService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlankDataAccess", Namespace="http://schemas.datacontract.org/2004/07/LOLAccountManagement")]
    [System.SerializableAttribute()]
    public partial class BlankDataAccess : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlankDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BlankIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Test_Interface.LOLService.GeneralError> ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BlankData {
            get {
                return this.BlankDataField;
            }
            set {
                if ((object.ReferenceEquals(this.BlankDataField, value) != true)) {
                    this.BlankDataField = value;
                    this.RaisePropertyChanged("BlankData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BlankID {
            get {
                return this.BlankIDField;
            }
            set {
                if ((this.BlankIDField.Equals(value) != true)) {
                    this.BlankIDField = value;
                    this.RaisePropertyChanged("BlankID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Test_Interface.LOLService.GeneralError> Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="General.Error", Namespace="http://schemas.datacontract.org/2004/07/LOLAccountManagement")]
    [System.SerializableAttribute()]
    public partial struct GeneralError : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorTitleField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescription {
            get {
                return this.ErrorDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescriptionField, value) != true)) {
                    this.ErrorDescriptionField = value;
                    this.RaisePropertyChanged("ErrorDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorLocation {
            get {
                return this.ErrorLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorLocationField, value) != true)) {
                    this.ErrorLocationField = value;
                    this.RaisePropertyChanged("ErrorLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorNumber {
            get {
                return this.ErrorNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorNumberField, value) != true)) {
                    this.ErrorNumberField = value;
                    this.RaisePropertyChanged("ErrorNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorTitle {
            get {
                return this.ErrorTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorTitleField, value) != true)) {
                    this.ErrorTitleField = value;
                    this.RaisePropertyChanged("ErrorTitle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="LOLService.ReliantDataConnect")]
    public interface ReliantDataConnect {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ReliantDataConnect/BlankDataAccessGetByText", ReplyAction="urn:ReliantDataConnect/BlankDataAccessGetByTextResponse")]
        System.Collections.Generic.List<Test_Interface.LOLService.BlankDataAccess> BlankDataAccessGetByText(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ReliantDataConnect/BlankDataAccessGetSpecific", ReplyAction="urn:ReliantDataConnect/BlankDataAccessGetSpecificResponse")]
        Test_Interface.LOLService.BlankDataAccess BlankDataAccessGetSpecific(int blankID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ReliantDataConnect/LookupsSave", ReplyAction="urn:ReliantDataConnect/LookupsSaveResponse")]
        Test_Interface.LOLService.BlankDataAccess LookupsSave(Test_Interface.LOLService.BlankDataAccess blankDataAccess);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ReliantDataConnect/BlankDataAccessDelete", ReplyAction="urn:ReliantDataConnect/BlankDataAccessDeleteResponse")]
        System.Collections.Generic.List<Test_Interface.LOLService.GeneralError> BlankDataAccessDelete(Test_Interface.LOLService.BlankDataAccess blankDataAccess);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReliantDataConnectChannel : Test_Interface.LOLService.ReliantDataConnect, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReliantDataConnectClient : System.ServiceModel.ClientBase<Test_Interface.LOLService.ReliantDataConnect>, Test_Interface.LOLService.ReliantDataConnect {
        
        public ReliantDataConnectClient() {
        }
        
        public ReliantDataConnectClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReliantDataConnectClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReliantDataConnectClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReliantDataConnectClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Test_Interface.LOLService.BlankDataAccess> BlankDataAccessGetByText(string searchString) {
            return base.Channel.BlankDataAccessGetByText(searchString);
        }
        
        public Test_Interface.LOLService.BlankDataAccess BlankDataAccessGetSpecific(int blankID) {
            return base.Channel.BlankDataAccessGetSpecific(blankID);
        }
        
        public Test_Interface.LOLService.BlankDataAccess LookupsSave(Test_Interface.LOLService.BlankDataAccess blankDataAccess) {
            return base.Channel.LookupsSave(blankDataAccess);
        }
        
        public System.Collections.Generic.List<Test_Interface.LOLService.GeneralError> BlankDataAccessDelete(Test_Interface.LOLService.BlankDataAccess blankDataAccess) {
            return base.Channel.BlankDataAccessDelete(blankDataAccess);
        }
    }
}
